### ISSUE TITLE
Using mtcp created fd's across different mtcp context work?

### ISSUE THREAD

**Issue by arunkumarsit** [eunyoung14/mtcp#44]
Hi,

I noticed that the socket fd's created inside a mtcp context are bound to that specific mtcp context and cannot be used by other mtcp context. Is my understanding is right?

I am facing the following problem
- Thread-1 tries to accept the connections from clients for a AF_INET socket. The mtcp sockets are created in the mtcp context manager say mtcp[0]. Thread-1 waits in mtcp_epoll_wait() operation for accept events to occur.
- After connection is accepted, Thread-2 will register the new fd and does mtcp_epoll_wait() for all the accepted fd's. (based on load, I can increase the thread counts to handle new connections). 

Ideally there are 2 threads, one thread is accepting connection using mtcp_epoll_wait and second thread is handling the vents to the accepted connections based on events triggered in mtcp_epoll_wait.
(I hope this is a common design for handling connections asynchronously).

As 2 threads are using mtcp_epoll_wait() simultaneously, I can't use the same mtcp context for both the threads (as the mtcp manager has only one epoll event pointer for it). So what could be the suggestion now? 
Will creation of new mtcp context manager helps in this scenario? If so, the accepted fd's are created in mtcp context manager [0]. Can I use the socket fd's created bu context 0 to new context 1 ?

How it is handled in mtcp ported applications ?

**Comment by ajamshed** [comment]
Hi Arun,

We always used one mTCP context and manager (per core) for all our ported applications. We designed our stack based on the assumption that only one thread will access the underlying data structures specific to the mTCP manager. I suggest that you stick with the single thread model because creating a duplicate mtcp manager would also create a separate pool of sockets.

Please note that creating multiple threads always create an extra overhead for the CPU (due to
inter-thread scheduling). You should try implementing your (mTCP-related) logic within the same thread for consistency and performance reasons.

**Comment by arunkumarsit** [comment]
Hi Asim,

Thanks for your inputs. I can understand the mtcp design that it focuses on user space packet handling and performance.
I see a common practice in applications that are using one thread for accepting client connections and other thread for handling the accepted connections. In this model, we have 2 thread each waiting for their own events to occur.

So how mtcp application is ported in those applications? Can you please explain me how mtcp is integrated in lighthttpd application (which is a multi-threaded application). It would be more helpful for me.

**Comment by ajamshed** [comment]
Hi Arun,
Most of our work argues against the employment of pipelining model (the one you are proposing) in favor of single-thread-does-all model (aka peer threading model) due to performance reasons. Newer applications are also following this mode of operations, e.g.

Nginx: http://stackoverflow.com/questions/3436808/how-does-nginx-handle-http-requests
Suricata (worker model): https://home.regit.org/2012/07/suricata-to-10gbps-and-beyond/

We ported or updated those applications that follow peer threading model. I suggest that (if possible) you also build mTCP application ports in this fashion.. or at least modify applications to adhere to this model.

If you still want to implement pipelining model, I suggest that you use some kind of inter-thread communication (e.g. via shared atomic variables) to transport events (such as MTCP_EPOLLOUT, MTCP_EPOLLIN) from thread-1 to thread-2.

**Comment by arunkumarsit** [comment]
Hi Asim,
I planned to move to single-threaded model as suggested by you. I made changes to my application and single thread handles all the connections.
But I noticed that (in mtcp_listen()) there is only one listener per mtcp context. 
`mtcp->listener = listener;`

That means I can use only one server socket per mtcp context? can't we use 4 server sockets in one thread in this scenario and listen for all the created fd's ?
To create multiple server sockets, do I need to create multiple mtcp context?

Please clarify my doubt on this.

**Comment by ajamshed** [comment]
You are right. The current mTCP stack has a restriction that it can bind to only one port per context. But this implementation can be extended to support multiple port bindings. You can probably give it a try. You will have to update core.c, tcp_in.c and api.c files. I guess we will eventually implement this feature in the future as well.

Creating multiple server sockets with multiple mtcp contexts may not work due to reasons we have already discussed.

**Comment by arunkumarsit** [comment]
Thank you very much for your inputs. And sorry to trouble you again !
I checked the files and identified the places to do the changes.
But still what I am not sure is that, the function Handle_TCP_ST_SYN_RCVD() is getting the cur_stream (which is a tcp_stream packet) and by default after inserting data into listener's acceptq, the event is triggered for mtcp_event_queue.
But in case of multiple listener queue's I need to know the socket id (where I can map the listener's according to scoket id.. even in all the socket structure the listener reference exist now ). But for incoming tcp_stream we have the sockt pointer as NULL. due to this I can't able to identify the corresponding listener and trigger the event.
Can you please suggest me good idea to find out the corresponding listener among multiple listeners in Handle_TCP_ST_SYN_RCVD() API?

**Comment by eunyoung14** [comment]
Hi Arun,
you may be able to create multiple listening sockets using `mtcp_listen()`. Even though the sockets for incoming streams are not yet created (set to null), if you find the right listening socket, you will be able to raise the event using it.)

In current implementation, the mapping to listener (`mtcp->listener`) is fixed and you cannot map multiple listeners. I suggest you to make this mapper to have multiple values.

See `mtcp_listen()` in api.c

```
mtcp->listener = listener;
```

When you are creating new listener in this function, make this listener to have multiple mappings. One suggestion is to make an array which indexes the listeners by the listening ports. After that, you will be able to find the listener at `Handle_TCP_ST_SYN_RCVD()`.

The code that you will need to touch would be as follows.
* `struct mtcp_manager` -> `struct tcp_listener *listener`
* `mtcp_listen()` in api.c
* `FilterSYNPacket()` in tcp_in.c
* `Handle_TCP_ST_SYN_RCVD()` in tcp_in.c
* `InterruptApplications()` in core.c

**Comment by arunkumarsit** [comment]
Hi,

Thanks for your support ! 
I have done the necessary changes (and some tweaks) and it is working fine.
I tried to integrate mtcp with NFS server application. I have seen that the NFS mount is successful after the listener modifications in mtcp and modifying design of NFS for **"single-threaded"** model.
Still I have to check with all other NFS related operations.

I still have a query that how mtcp can be integrated to the processes like NFS which are using pipeline model.
The reason for this question is that.. I planned to integrate/modify some other applications similar to NFS (say Samba server) with mtcp support. But modifying the design approach of all these applications seems not a good idea. 
So does mtcp faced similar kind of issues? does mtcp support multi-threaded (pipeline model) applications by doing any kind of tweaks?
How about tweaking the code for any one of the following options
- making socket fd's global, so that I can avoid the binding of fd's into one mtcp context. This will let multiple mtcp contexts to operate on any fd's we create
- Creation of multiple epoll fd's within same mtcp context. This will let us create multiple epoll fd's for mtcp context which is similar to Kernel epoll events. This will avoid creation of multiple mtcp context

Kindly let me know your inputs on this.
